name: hello-world
on: workflow_dispatch
jobs:
  install-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
      - run: npm ci
      - run: npm run cypress:run
