name: e2e-tests
on: workflow_dispatch
jobs:
    install-and-run-tests:
        env:
            CYPRESS_WP_USER1: ${{ secrets.WP_USER1 }}
            CYPRESS_WP_USER1_PASSWORD: ${{ secrets.WP_USER1_PASSWORD }}
            CYPRESS_WP_ADMIN: ${{ secrets.WP_ADMIN }}
            CYPRESS_WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: see ENVS
              run: env
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: package
                path: package.json
            - name: Get build aftifacts
              uses: actions/download-artifact@v3
              with:
                name: package
            - name: Cypress run tests
              uses: cypress-io/github-action@v6
              env: 
                CYPRESS_WP_USER1: ${{ secrets.WP_USER1 }}
                CYPRESS_WP_USER1_PASSWORD: ${{ secrets.WP_USER1_PASSWORD }}
                CYPRESS_WP_ADMIN: ${{ secrets.WP_ADMIN }}
                CYPRESS_WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
              with:
                browser: chrome
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: videos
                path: cypress/videos
            - name: Get build aftifacts
              uses: actions/download-artifact@v3
              with:
                name: videos
