name: testCMD
on: workflow_dispatch
jobs:
    testCmd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout another private repository
              uses: actions/checkout@v2
              with:
                  repository: AHWamboo/cypress-wamboo-demo-online-sql-dump
                  token: ${{ secrets.ACCESS_TOKEN }}
                  ref: main

            - name: List contents of the private repository
              run: |
                ls 

            - name: Decrypt File
              run: |
                gpg --quiet --decrypt --cipher-algo AES256 --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output db-backup.sql db-backup.sql.gpg
              env:
                GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

            - name: List contents of the private repository
              run: |
                ls 
