name: testCMD
on: workflow_dispatch
jobs:
    testCmd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout another private repository
              uses: actions/checkout@v2
              with:
                  repository: AHWamboo/cypress-wamboo-demo-online-sql-dump
                  # token: ${{ secrets.ACCESS_TOKEN }}
                  ref: main

            - name: List contents of the private repository
              run: |
                ls -la AHWamboo/cypress-wamboo-demo-online-sql-dump
