name: e2e-tests
on: workflow_dispatch
jobs:
    install-and-run-tests:
        env:
            WP_USER1: ${{ secrets.WP_USER1 }}
            WP_USER1_PASSWORD: ${{ secrets.WP_USER1_PASSWORD }}
            WP_ADMIN: ${{ secrets.WP_ADMIN }}
            WP_ADMIN_PASSWORD: ${{ secrets.WP_ADMIN_PASSWORD }}
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install dependencies
              uses: actions/setup-node@v4
              with:
                  node-version: 20.8.1
            - run: npm ci
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: package
                path: package.json
            - name: Get build aftifacts
              uses: actions/download-artifact@v3
              with:
                name: package
            - run: npm run cypress:run:ci
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: screens
                path: cypress/tsconfig.json
            - name: Get build aftifacts
              uses: actions/download-artifact@v3
              with:
                name: screens
