name: testCMD
on: workflow_dispatch
jobs:
    testCmd:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout another private repository
              uses: actions/checkout@v2
              with:
                  repository: AHWamboo/cypress-wamboo-demo-online-sql-dump
                  token: ${{ secrets.ACCESS_TOKEN }}
                  ref: main

            - name: List contents of the private repository
              run: |
                ls 

            - name: Decrypt File
              run: |
                gpg --batch --decrypt --cipher-algo AES256 --pinentry-mode loopback --passphrase "${{ secrets.GPG_PASSPHRASE }}" --output db-backup.sql db-backup.sql.gpg
              env:
                GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

            - name: List contents of the private repository
              run: |
                ls 

            - name: run database backup
              run: |
                mysql -h ${{ env.DB_HOSTNAME }} -u ${{ env.DB_USERNAME }} -p'${{ env.DB_PASSWORD }}' --max_allowed_packet=256M -D ${{ env.DB_NAME }} --force < db-backup.sql;
              env:
                DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
                DB_USERNAME: ${{ secrets.DB_USERNAME }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}
